CommunityWeb/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration for CommunityWeb project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import apps.app_demo.views

urlpatterns = [
    path('', apps.app_demo.views.index),
    path('admin/', admin.site.urls),
    path('topic/', include('apps.app_demo.urls')),
    path('case/', include('apps.excellentCase.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/app_demo/models.py
# -*- coding: utf-8 -*-
from ckeditor.fields import RichTextFormField
from django.contrib.auth.models import AbstractUser

# Create your models here.
from django.db import models
from django.utils import timezone


# 用户
class User(AbstractUser):
    """User model"""
    USER_TYPE_CHOICES = [
        ('villager', '村庄'),
        ('young_adult', '年轻人'),
        ('college_student', '大学生'),
        ('research_team', '科研团队'),
        ('business', '企业'),
    ]

    GENDER_CHOICES = [
        ('male', '男'),
        ('female', '女'),
    ]

    UserID = models.AutoField(primary_key=True)
    remarks = models.CharField(max_length=500, null=True, blank=True, default="该用户暂未设置签名")
    # Email = models.CharField(max_length=255, unique=True)
    User_Type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)
    Gender_user = models.CharField(max_length=20, choices=GENDER_CHOICES)

    image = models.ImageField(upload_to='images/%Y/%m', default='images/default.png', max_length=100,
                              verbose_name="用户头像")

    class Meta:
        verbose_name = "用户资料"
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.User_Type
        return self.username  # 给评论作者为用户名


class Category(models.Model):
    """ 博客的分类模型 """
    name = models.CharField(max_length=32, verbose_name="分类名称")
    desc_category = models.TextField(max_length=200, blank=True, default='', verbose_name="分类描述")

    class Meta:
        verbose_name = "帖子分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 论坛
class Topic(models.Model):
    """博客的话题模型"""
    title = models.CharField(max_length=100, null=True, blank=True, verbose_name="标题")
    desc_topic = models.TextField(blank=True, default='', verbose_name="文章描述")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    # content = models.TextField(max_length=20000, blank=True, default='', verbose_name="内容")
    content = models.TextField(max_length=20000, blank=True, default='', verbose_name="内容")
    # 创建时间，默认为当前时间
    time = models.DateTimeField(default=timezone.now, verbose_name="创建时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")
    # 作者，与 'User' 模型关联 就是外键
    author = models.ForeignKey('User', related_name='topic_author', on_delete=models.CASCADE, null=True,
                               blank=True, verbose_name="作者")
    # 评论数量，默认为0
    remarks = models.PositiveIntegerField(default=0, verbose_name="评论数量")
    # 浏览次数，默认为0
    views = models.PositiveIntegerField(default=0, verbose_name="浏览数量")

    class Meta:
        verbose_name = "论坛帖子"
        verbose_name_plural = verbose_name

    def __str__(self):
        # 返回主题的内容作为字符串表示
        return self.content

    def increase_remarks(self):
        # 增加评论数量
        self.remarks += 1
        self.save(update_fields=['remarks'])

    def increase_views(self):
        # 增加浏览次数
        self.views += 1
        self.save(update_fields=['views'])


# from ckeditor.fields import RichTextField
# 需要上传图片功能
from ckeditor_uploader.fields import RichTextUploadingField


class TopicComment(models.Model):
    """帖子评论的模型"""
    # 外键关联到主题（Topic），当主题被删除时，相关的评论也会被删除
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, null=True, blank=True)

    # 外键关联到自身，用于表示评论的回复关系，当评论被删除时，相关的回复也会被删除
    comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    body = models.TextField(max_length=20000, blank=True, default='', verbose_name="内容")

    # 评论时间，默认为当前时间
    time = models.DateTimeField(default=timezone.now)

    # 外键关联到用户，表示评论的作者，当用户被删除时，相关的评论也会被删除
    author = models.ForeignKey('User', related_name='TopicComment_Author', on_delete=models.CASCADE, null=True,
                               blank=True)

    class Meta:
        verbose_name = "帖子评论"
        verbose_name_plural = verbose_name
        ordering = ('time',)

    def __str__(self):
        return self.body[:20]


class PrivateMessage(models.Model):
    """私信模型"""
    sender = models.ForeignKey('User', related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey('User', related_name='received_messages', on_delete=models.CASCADE)
    content = models.TextField()  # TextField 存储更长
    timestamp = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)  # 布尔表示消息是否已读

    def __str__(self):
        return f"From {self.sender} to {self.receiver} at {self.timestamp}"

    class Meta:
        ordering = ['-timestamp']  # 根据时间戳倒序排序私信
        verbose_name = "私信"
        verbose_name_plural = verbose_name

templates/forum/add_topic.html
<!--fxx-->
<!--Author: FxDr-->
<!--Created Time: 2023/10/29 15:40-->
<!--Filename: add_topic.html -->
{% extends "base.html" %}

{% block content %}
    <section>
        <h2>Add a New Topic</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %} {# 添加 CSRF 令牌 #}
            {{ form.as_p }} {# 使用表单字段渲染表单 #}
            <button type="submit">Submit</button>
        </form>
    </section>
{% endblock %}

templates/forum/category_topic.html
{% extends "base.html" %}
<!-- category.html -->

{% block content %}
    <section class="forum-section">
        <h2>话题列表</h2>

        <div class="row">
            <div class="col-md-3">
                <ul class="dropdown-menu">
                    <li><a href="{% url 'category' 1 %}">产业振兴</a></li>
                    <li><a href="{% url 'category' 2 %}">人才振兴</a></li>
                    <li><a href="{% url 'category' 3 %}">文化振兴</a></li>
                    <li><a href="{% url 'category' 4 %}">生态振兴</a></li>
                    <li><a href="{% url 'category' 5 %}">组织振兴</a></li>
                </ul>
            </div>
            <div class="col-md-9">
                <ul class="topic-list">
                    {% for topic in topics %}
                        <li class="topic-item">
                            <h3 class="topic-title">{{ topic.title }}</h3>
                            <p class="topic-content">{{ topic.content }}</p>
                            <p class="topic-info">作者: {{ topic.author }}</p>
                            <p class="topic-info">分类: {{ topic.category.name }}</p>
                            <p class="topic-info">发布时间: {{ topic.time }}</p>
                            <p class="topic-info">评论数: {{ topic.remarks }}</p>
                            <p class="topic-info">浏览次数: {{ topic.views }}</p>
                            <a class="btn btn-info" href="{% url 'topic' topic.id %}">查看详情</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

templates/forum/forum.html
{% extends "base.html" %}
<!-- forum.html -->

{% block content %}
    <section class="forum-section">
        <h2>欢迎来到论坛</h2>
        <!-- 添加“发布帖子”按钮 -->
        <button><a href="{% url 'add_topic' %}">发布帖子</a></button>
        <button><a href="{% url 'forum' %}">最新发布</a></button>
        <!--根据评论数来排序 -->
        <button><a href="{% url 'hot_topic' %}">最热话题</a></button>
        <button><a href="{% url 'my_topic' %}">我的发布</a></button>

        <ul class="topic-list">
            {% for topic in latest_topic %}
                <li class="topic-item">
                    <h3 class="topic-title">{{ topic.title }}</h3>
{#                    <p class="topic-content">{{ topic.content }}</p>#}
                    <p class="topic-info">作者: {{ topic.author }}</p>
                    <p class="topic-info">分类: {{ topic.category.name }}</p>
                    <p class="topic-info">发布时间: {{ topic.time }}</p>
                    <p class="topic-info">评论数: {{ topic.remarks }}</p>
                    <p class="topic-info">浏览次数: {{ topic.views }}</p>
                    <!-- 添加“查看详情”按钮 -->
                    <a class="btn btn-info" href="{% url 'topic' topic.id %}">查看详情</a>
                </li>
            {% endfor %}
        </ul>

        <!-- 分页导航 -->
        <div class="pagination">
            <span class="step-links">
                {% if latest_topic.has_previous %}
                    <a class="btn btn-secondary" href="?page=1">&laquo; 第一页</a>
                    <a class="btn btn-secondary" href="?page={{ latest_topic.previous_page_number }}">上一页</a>
                {% endif %}

                <span class="current-page">第 {{ latest_topic.number }} 页</span>

                {% if latest_topic.has_next %}
                    <a class="btn btn-secondary" href="?page={{ latest_topic.next_page_number }}">下一页</a>
                    <a class="btn btn-secondary"
                       href="?page={{ latest_topic.paginator.num_pages }}">最后一页 &raquo;</a>
                {% endif %}
            </span>
        </div>
    </section>
{% endblock %}

templates/forum/hot_topic.html
<!--fxx-->
<!--Author: FxDr-->
<!--Created Time: 2023/10/29 17:17-->
<!--Filename: hot_topic.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section>
        <h2>热门主题</h2>
        <!-- 添加“发布帖子”按钮 -->
        <button><a href="{% url 'add_topic' %}">发布帖子</a></button>
        <button><a href="{% url 'forum' %}">最新发布</a></button>
        <!--根据评论数来排序 -->
        <button><a href="{% url 'hot_topic' %}">最热话题</a></button>
        <button><a href="{% url 'my_topic' %}">我的发布</a></button>
        <ul>
            {% for topic in latest_topic %}
                <li>
                    <h3>标题:{{ topic.title }}</h3>
                    <p>文章描述:{{ topic.desc_topic }}</p>
                    {#                    <p>内容:{{ topic.content }}</p>#}
                    <p>作者: {{ topic.author }}</p>
                    <p>分类: {{ topic.category.name }}</p>
                    <p>发布时间: {{ topic.time }}</p>
                    <p>评论数量: {{ topic.remarks }}</p>
                    <p>浏览次数: {{ topic.views }}</p>
                    <!-- 添加“查看详情”按钮 -->
                    <a class="btn btn-info" href="{% url 'topic' topic.id %}">查看详情</a>
                </li>
            {% endfor %}
        </ul>

        <!-- 分页导航 -->
        <div class="pagination">
            <span class="step-links">
                {% if latest_topic.has_previous %}
                    <a href="?page=1">&laquo; 第一页</a>
                    <a href="?page={{ latest_topic.previous_page_number }}">上一页</a>
                {% endif %}

                <span class="current-page">第 {{ latest_topic.number }} 页</span>

                {% if latest_topic.has_next %}
                    <a href="?page={{ latest_topic.next_page_number }}">下一页</a>
                    <a href="?page={{ latest_topic.paginator.num_pages }}">最后一页 &raquo;</a>
                {% endif %}
            </span>
        </div>
    </section>
{% endblock %}

templates/forum/search_results.html
<!--fxx-->
<!--Author: FxDr-->
<!--Created Time: 2023/11/15 17:59-->
<!--Filename: search_results.html -->
{% extends 'base.html' %}

{% block content %}
    <h2>搜索结果</h2>
    <p>显示与关键字 "{{ query }}" 相关的结果：</p>

    {% for result in results %}
        <div class="topic-item">
            <h3 class="topic-title">{{ result.title }}</h3>
            <p class="topic-info">作者: {{ result.author }}</p>
            <p class="topic-info">分类: {{ result.category.name }}</p>
            <p class="topic-info">发布时间: {{ result.time }}</p>
            <p class="topic-info">评论数: {{ result.remarks }}</p>
            <p class="topic-info">浏览次数: {{ result.views }}</p>
            <a class="btn btn-info" href="{% url 'topic' result.id %}">查看详情</a>
        </div>
    {% empty %}
        <p>没有找到相关结果。</p>
    {% endfor %}
{% endblock %}

templates/forum/topic.html
<!--fxx-->
<!--Author: FxDr-->
<!--Created Time: 2023/10/29 16:46-->
<!--Filename: topic.html -->
{% extends "base.html" %}

{% block content %}
    <section>
        <h3>标题: {{ topic.title }}</h3>
        <p>文章描述: {{ topic.desc_topic }}</p>
        <p>作者: {{ topic.author }}</p>
        <p>分类: {{ topic.category.name }}</p>
        <p>发布时间: {{ topic.time }}</p>
        <p>最后修改时间: {{ topic.pub_date }}</p>
        <p>文章内容:{{ topic.content }}</p>
        <p>评论数量: {{ topic.remarks }}</p>
        <p>浏览次数: {{ topic.views }}</p>
    </section>

    <!-- 显示主题的评论 -->
    <section>
        <h3>评论</h3>
        <ul>
            {% for comment in topic.topiccomment_set.all %}
                <li>
                    <img src="{{ comment.author.image.url }}" alt="User Avatar" style="width: 70px; height: 70px;">
                    <!-- 显示评论作者的头像 -->
                    <p>{{ comment.body }}</p>
                    <p>作者: {{ comment.author }}</p>
                    <p>评论时间: {{ comment.time }}</p>
                </li>
            {% endfor %}
        </ul>
    </section>

    <!-- 添加评论表单 -->
    <section>
        <h3>添加评论</h3>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">提交评论</button>
        </form>
    </section>
{% endblock %}

templates/forum/user_topics.html
{% extends "base.html" %}

{% block content %}
    <section>
        <h2>我发布的帖子</h2>
        <!-- 添加“发布帖子”按钮 -->
        <button><a href="{% url 'add_topic' %}">发布帖子</a></button>
        <button><a href="{% url 'forum' %}">最新发布</a></button>
        <!--根据评论数来排序 -->
        <button><a href="{% url 'hot_topic' %}">最热话题</a></button>
        <button><a href="{% url 'my_topic' %}">我的发布</a></button>
        <ul>
            {% for topic in user_topics %}
                <li>
                    <h3>标题:{{ topic.title }}</h3>
                    <p>文章描述:{{ topic.desc_topic }}</p>
                    <p>作者: {{ topic.author }}</p>
                    <p>分类: {{ topic.category.name }}</p>
                    <p>发布时间: {{ topic.time }}</p>
                    <p>评论数: {{ topic.remarks }}</p>
                    <p>浏览次数: {{ topic.views }}</p>
{#                    <p>文章内容:{{ topic.content }}</p>#}
                    <a class="btn btn-info" href="{% url 'topic' topic.id %}">查看详情</a>
                </li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}